server {
    listen 8080;            # Port
    server_name localhost;  # Nom du serv
    host 127.0.0.1;         # Ip
    root ./www;             # Dossier ou sont les fichiers
    index index.html;       # Fichier par defaut si path = /

    # Page d'erreur personalisee si 0 snus
    #   error_page 404 error_pages/404SnusNotFound.html
    # Location / -> location par defaut
    #   allow_methods GET POST      -> on permet les methods GET/POST dans le dossier /, le dossier par defaut
    #   autoindex off/on        -> on = on liste les fichiers si on ne trouve pas l'image specifique
    #                           -> off = on ne liste pas les fichiers si on ne trouve pas l'image mais on renvoie error 404SnusNotFound
    # Location /image {}    -> location(dossier) des images
    # Location /Snus {}     -> location(dossier) des snus
    # CGI
}

server {
    listen 8081;
    server_name localhost2;
    host 127.0.0.1;
    root ./default/test/caca.txt;
}

server {
    listen 1025;
    server_name localhost3;
    host 127.0.0.1;
    root ./snus/snus/velo;
}