server {
    listen 8080;
    server_name localhost;
    host 127.0.0.1;
    root a;
}

server {
    listen 8081;
    server_name localhost;
    host 127.0.0.1;
    root ./default/test/caca.txt;
}

server {
    listen 1025;
    server_name localhost;
    host 127.0.0.1;
    root ./snus/snus/velo;
}