server {
	listen 8080;
	server_name Web&Socket;

	root ./www;

	client_max_body_size 3000000;

	error_page 403 error_pages/403.html;
	error_page 404 error_pages/404.html;
	error_page 405 error_pages/405.html;
	error_page 413 error_pages/413.html;
	error_page 501 error_pages/500.html;

	location / {
		index index.html;
		allowed_methods GET POST;
		autoindex off;
	}

	location /images {
		allowed_methods GET;
		autoindex on;
	}

	location /uploads {
		index uploads.html;
		allowed_methods GET POST DELETE;
		autoindex on;
	}

	location /error_pages {
		allowed_methods GET;
		autoindex on;
	}

	location /old {
		allowed_methods GET;
		return 301 /new;
	}

	location /sort {
		allowed_methods GET POST;
		cgi_extension .cgi;
	}
}

server {
	listen 8081;
	server_name tetris;

	root ./www/tetris;

	client_max_body_size 1000;

	error_page 404 error_pages/404.html;
	error_page 413 error_pages/413.html;
	error_page 500 error_pages/500.html;

	location / {
		index tetris.html;
		allowed_methods GET;
		autoindex off;
	}

	location /images {
		autoindex on;
	}

	location /uploads {
		autoindex off;
	}

	location /error_pages {
		allowed_methods GET;
		autoindex off;
	}

	location /cgi-bin {
		allowed_methods GET POST;
		cgi_extension .cgi;
	}
}